services:
  # In order to run, you need to build the services from the dockerfiles in this repository
  db:
    image: soundtrackd-db
    container_name: soundtrackd-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
  api:
    image: soundtrackd-api
    container_name: soundtrackd-api
    restart: always
    ports:
      - 5345:5345