pip install annotated-types
pip install anyio
pip install ascii-magic
pip install certifi
pip install charset-normalizer
pip install -U  click
pip install colorama
pip install python-dotenv 
pip install exceptiongroup
pip install fastapi
pip install h11
pip install idna
pip install mysql-connector-python
pip install pillow
pip install pydantic
pip install pydantic_core
pip install requests
pip install sniffio
pip install starlette
pip install typing_extensions
pip install urllib3
pip install uvicorn
