POST http://0.0.0.0:5345/users/register
content-type: application/json

{
  "username": "string",
  "email": "user@example.com",
  "password": "string",
  "password_confirmation": "string"
}

###

GET http://0.0.0.0:5345/users/list


###

GET http://0.0.0.0:5345