POST https://soundtrackd-api.ewitsdonovan.com/users/register
content-type: application/json

{
  "username": "string",
  "email": "user@example.com",
  "password": "string",
  "password_confirmation": "string"
}

###

GET http://localhost:5345/users/list
###

GET http://localhost:5345/search/album?q=Panic


###

GET http://localhost:5345

###

GET https://soundtrackd-api.ewitsdonovan.com/users/list